### ISSUE TITLE
Complete Rewrite

### ISSUE THREAD

**Issue by cwilson15205** [cwilson15205/HW.WilsonC#40]
- [ ] Convert assignment status to number format.
- [ ] TODO #1 Convert row['assignment'] to row['name']
- [x] TODO #2 Make the row status formatting a function
- [ ] TODO #3 Make Return location a function
- [ ] TODO User group permissions system
- [ ] Multi paged SQL response's
- [ ] SQL response sorting
- [ ] Add fd/rescue/public safety functions
- [ ] Convert site to sophomore year
